Repository Yellobook/yellobook-backend, pull requests merged in 2024-07, with the labels that each got.

#3 [Feature/YB-10] HTTP 로깅 구축
  yellobook-api/src/main/java/com/yellobook/domain/auth/service/AuthService.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/service/JwtService.java
  yellobook-common/src/main/java/com/yellobook/error/code/AuthErrorCode.java
  yellobook-common/src/main/java/com/yellobook/error/code/CommonErrorCode.java
  yellobook-common/src/main/java/com/yellobook/error/code/ErrorCode.java
  yellobook-common/src/main/java/com/yellobook/error/exception/CustomException.java
  yellobook-common/src/main/java/com/yellobook/error/handler/GlobalExceptionHandler.java
  yellobook-common/src/main/java/com/yellobook/logging/ReqResLoggingFilter.java
  yellobook-common/src/main/java/com/yellobook/logging/dto/HttpLogMessage.java
  yellobook-common/src/main/java/com/yellobook/response/ResponseFactory.java
  yellobook-common/src/main/resources/logback-spring.xml
Labels: ⚙️config, ✨feature

#4 [Feature/YB-9] 헬스 체크 컨트롤러 구성
  yellobook-api/src/main/java/com/yellobook/common/anonotation/ApiV1Controller.java
  yellobook-api/src/main/java/com/yellobook/common/controller/HealthController.java
Labels: ✨feature

#6 [Feature/YB-20] ELK + Filebeat 로그 모니터링 추가
  .gitignore
  infrastructure/database/.env.example
  infrastructure/database/docker-compose.yml
  infrastructure/monitoring/docker-compose.yml
  infrastructure/monitoring/filebeat/filebeat.yml
  infrastructure/monitoring/logstash/logstash.conf
  yellobook-common/src/main/resources/logback-spring.xml
Labels: ⚙️config, 🧤Infra, ♻️refactor, ✨feature

#9 [Feature/YB-48] Swagger 설정
  yellobook-api/src/main/java/com/yellobook/common/controller/HealthController.java
  yellobook-api/src/main/java/com/yellobook/config/SecurityConfig.java
  yellobook-api/src/main/java/com/yellobook/config/SwaggerConfig.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/controller/TokenController.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/dto/TokenResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/security/filter/JwtAuthFilter.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/security/oauth2/dto/OAuth2UserDTO.java
  yellobook-common/build.gradle
  yellobook-common/src/main/java/com/yellobook/response/BaseResponse.java
  yellobook-common/src/main/java/com/yellobook/response/ErrorResponse.java
  yellobook-common/src/main/java/com/yellobook/response/SuccessResponse.java
  yellobook-domain/src/main/java/com/yellobook/enums/MemberRole.java
Labels: 📝docs

#10 [Feature/YB-50]: 재고도메인 초기세팅
  yellobook-api/src/main/java/com/yellobook/domain/inventory/controller/InventoryController.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/dto/AddProductRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/dto/GetProductsResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/dto/GetTotalInventoryResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/dto/ModifyProductAmountRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/service/InventoryCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/service/InventoryQueryService.java
  yellobook-domain/src/main/java/com/yellobook/domains/announce/entity/AnnounceComment.java
  yellobook-domain/src/main/java/com/yellobook/domains/common/entity/Post.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/dto/InventoryDTO.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/dto/ProductDTO.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/entity/Inventory.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/entity/Product.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/InventoryRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/InventoryRepositoryCustom.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/InventoryRepositoryCustomImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/ProductRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/ProductRepositoryCustom.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/ProductRepositoryCustomImpl.java
Labels: ✨feature

#11 [Feature/YB-51] 멤버 도메인 초기 설정
  yellobook-api/src/main/java/com/yellobook/domain/member/controller/MemberController.java
  yellobook-api/src/main/java/com/yellobook/domain/member/dto/MemberResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberQueryServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberService.java
Labels: ✨feature

#12 [Feature/YB-52] 팀 도메인 초기 세팅
  yellobook-api/src/main/java/com/yellobook/domain/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domain/team/dto/TeamRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/team/dto/TeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamService.java
Labels: ✨feature

#13 [Feature/YB-53]: 주문도메인 초기세팅
  yellobook-api/src/main/java/com/yellobook/domain/announce/controller/AnnounceController.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/service/AnnounceCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/service/AnnounceService.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/controller/InventoryController.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/service/InventoryCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/inventory/service/InventoryQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/order/controller/OrderController.java
  yellobook-api/src/main/java/com/yellobook/domain/order/service/OrderCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/order/service/OrderService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domain/work/controller/WorkController.java
  yellobook-api/src/main/java/com/yellobook/domain/work/service/WorkCommandService.java
  yellobook-domain/src/main/java/com/yellobook/domains/common/entity/Post.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/entity/Participant.java
Labels: ✨feature

#14 [Feature/YB-57]: 인증도메인 초기세팅
  yellobook-api/src/main/java/com/yellobook/domain/auth/controller/AuthController.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/service/AuthService.java
  yellobook-api/src/main/java/com/yellobook/domain/member/controller/MemberController.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberQueryServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/search/controller/SearchController.java
Labels: ✨feature

#16 [Feature/YB-55] 업무, 공지 도메인 초기 세팅
  yellobook-api/src/main/java/com/yellobook/domain/announce/controller/AnnounceController.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/dto/AnnounceCommentRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/dto/AnnounceCommentResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/dto/AnnounceRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/dto/AnnounceResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/service/AnnounceCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/service/AnnounceCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/service/AnnounceQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/announce/service/AnnounceQueryServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/work/controller/WorkController.java
  yellobook-api/src/main/java/com/yellobook/domain/work/dto/WorkCommentRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/work/dto/WorkCommentResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/work/dto/WorkRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/work/dto/WorkResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/work/service/WorkCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/work/service/WorkCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/work/service/WorkQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/work/service/WorkQueryServiceImpl.java
Labels: ✨feature

#17 [Feature/YB-54] 일정 도메인 초기세팅
  yellobook-api/src/main/java/com/yellobook/domain/schedule/controller/ScheduleController.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/request/DailyScheduleParam.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/request/MonthlyScheduleParam.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/request/SearchScheduleParam.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/response/DailyScheduleDTO.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/response/MonthlyTotalScheduleDTO.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/response/SearchMonthlyScheduleDTO.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/dto/response/UpcomingScheduleDTO.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/service/ScheduleService.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/vo/DailySchedulesVO.java
  yellobook-api/src/main/java/com/yellobook/domain/schedule/vo/ScheduleVO.java
  yellobook-api/src/main/java/com/yellobook/domain/search/controller/SearchController.java
  yellobook-api/src/main/java/com/yellobook/domain/search/dto/request/SearchScheduleDto.java
  yellobook-api/src/main/java/com/yellobook/domain/search/service/SearchService.java
Labels: ♻️refactor, ✨feature

#21 [Feature/YB-107]: 멤버 도매인 구현
  yellobook-api/src/main/java/com/yellobook/domain/member/controller/MemberController.java
  yellobook-api/src/main/java/com/yellobook/domain/member/dto/MemberResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/member/mapper/MemberMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/member/service/MemberQueryService.java
  yellobook-common/src/main/java/com/yellobook/error/code/MemberErrorCode.java
  yellobook-domain/src/main/java/com/yellobook/domains/member/entity/Member.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/dto/MemberJoinTeamDTO.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepositoryImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantRepository.java
Labels: ✨feature
