Repository Yellobook/yellobook-backend, pull requests merged in 2024-08, with the labels that each got.

#28 [Refactor/YB-193] 시큐리티 에러핸들링 개선
  yellobook-api/src/main/java/com/yellobook/config/SecurityConfig.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/security/filter/JwtAuthFilter.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/security/handler/CustomAccessDeniedHandler.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/security/handler/CustomAuthenticationEntryPoint.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/service/AuthService.java
  yellobook-common/src/main/java/com/yellobook/error/code/AuthErrorCode.java
Labels: ♻️refactor, ✨feature

#29 [Chore/YB-198] Jacoco 코드 커버리지 설정
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  build.gradle
Labels: ⚙️config

#23 [Feature/YB-108]: 주문 도메인 구현
  yellobook-api/src/main/java/com/yellobook/common/annotation/ExistOrder.java
  yellobook-api/src/main/java/com/yellobook/common/utils/ParticipantUtil.java
  yellobook-api/src/main/java/com/yellobook/common/validation/validator/ExistOrderValidator.java
  yellobook-api/src/main/java/com/yellobook/domain/order/controller/OrderController.java
  yellobook-api/src/main/java/com/yellobook/domain/order/dto/AddOrderCommentRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/order/dto/AddOrderCommentResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/order/dto/GetOrderCommentsResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/order/dto/GetOrderResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/order/dto/MakeOrderRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/order/dto/MakeOrderResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/order/mapper/OrderMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/order/service/OrderCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/order/service/OrderQueryService.java
  yellobook-common/src/main/java/com/yellobook/error/code/OrderErrorCode.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/entity/Product.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/dto/OrderCommentDTO.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/dto/OrderDTO.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/entity/Order.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/entity/OrderComment.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/entity/OrderMention.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/repository/OrderMentionRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/repository/OrderRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/repository/OrderRepositoryCustom.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/repository/OrderRepositoryCustomImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantRepository.java
Labels: ✨feature

#24 [Feature/YB-99] 팀 도메인 구현
  yellobook-api/build.gradle
  yellobook-api/src/main/java/com/yellobook/common/validation/annotation/ExistTeam.java
  yellobook-api/src/main/java/com/yellobook/common/validation/validator/TeamExistValidator.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/dto/InvitationResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/auth/service/RedisTeamService.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/service/InformCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/service/InformCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domain/team/dto/TeamRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/team/dto/TeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/team/mapper/ParticipantMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/team/mapper/TeamMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryServiceImpl.java
  yellobook-common/src/main/java/com/yellobook/error/code/TeamErrorCode.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantRepository.java
Labels: ✨feature

#30 [Feature/YB-100] 공지(업무) 도메인 구현
  yellobook-api/src/main/java/com/yellobook/common/annotation/ExistInform.java
  yellobook-api/src/main/java/com/yellobook/common/validator/ExistInformValidator.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/controller/InformController.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/dto/InformRequest.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/dto/InformResponse.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/dto/MentionDTO.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/mapper/CommentMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/mapper/InformMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/service/InformCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/service/InformCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/service/InformQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/inform/service/InformQueryServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domain/team/mapper/ParticipantMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryServiceImpl.java
  yellobook-common/src/main/java/com/yellobook/error/code/InformErrorCode.java
  yellobook-common/src/main/java/com/yellobook/error/code/MemberErrorCode.java
  yellobook-domain/src/main/java/com/yellobook/domains/inform/entity/InformComment.java
  yellobook-domain/src/main/java/com/yellobook/domains/inform/entity/InformMention.java
  yellobook-domain/src/main/java/com/yellobook/domains/inform/repository/InformCommentRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/inform/repository/InformMentionRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepositoryImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantRepository.java
Labels: ✨feature

#33 [Fix/YB-247] 팀 도메인 내 세부사항 변경
  yellobook-api/src/main/java/com/yellobook/domain/auth/service/RedisTeamService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domain/team/mapper/ParticipantMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/team/mapper/TeamMapper.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamCommandService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryService.java
  yellobook-api/src/main/java/com/yellobook/domain/team/service/TeamQueryServiceImpl.java
  yellobook-common/src/main/java/com/yellobook/error/code/TeamErrorCode.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/entity/Participant.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/entity/Team.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/TeamRepository.java
Labels: 🛠️bugfix

#37 [Feature/YB-236]: 사용자 도메인 Controller Unit Test 작성
  yellobook-api/src/test/java/com/yellobook/domain/member/controller/MemberControllerTest.java
Labels: ✨feature

#38 [Feature/YB-238]: 재고 도메인 Controller Unit Test 작성
  yellobook-api/src/test/java/com/yellobook/domain/inventory/controller/InventoryControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domain/member/controller/MemberControllerTest.java
Labels: ✅test

#39 [Feature/YB-240]: 주문 도메인 Controller Unit Test 작성
  yellobook-api/src/main/java/com/yellobook/domain/order/controller/OrderController.java
  yellobook-api/src/test/java/com/yellobook/domain/member/controller/MemberControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domain/order/controller/OrderControllerTest.java
Labels: ✅test

#42 [Feature/YB-222]: 재고 도메인 Repository Unit Test 작성
  yellobook-domain/src/test/java/com/yellobook/domain/inventory/InventoryRepositoryTest.java
Labels: ✅test

#46 [Test/YB-239]: 일정 도메인 Controller Unit Test 작성
  yellobook-api/src/main/java/com/yellobook/domains/schedule/dto/request/DailyParam.java
  yellobook-api/src/main/java/com/yellobook/domains/schedule/dto/request/MonthlyParam.java
  yellobook-api/src/main/java/com/yellobook/domains/schedule/dto/request/MonthlySearchParam.java
  yellobook-api/src/test/java/com/yellobook/domains/schedule/controller/ScheduleControllerTest.java
Labels: ✅test, 🛠️bugfix

#47 [Hotfix/YB-321] 공지(업무) 도메인 내 멘션DTO 수정
  yellobook-api/src/main/java/com/yellobook/domains/inform/dto/MentionDTO.java
Labels: 🚑hotfix

#48 [Hotfix/YB-329] 공지(업무) 도메인 매퍼 수정
  yellobook-api/src/main/java/com/yellobook/domains/team/mapper/ParticipantMapper.java
Labels: 🚑hotfix

#41 [Test/YB-223] 팀 도메인 Repository Unit Test 작성
  yellobook-api/src/main/java/com/yellobook/domains/inform/service/InformCommandServiceImpl.java
  yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/TeamRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/TeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/request/CreateTeamRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/request/InvitationCodeRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/CreateTeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/GetTeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/InvitationCodeResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/JoinTeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/LeaveTeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/mapper/TeamMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamCommandService.java
  yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamQueryService.java
  yellobook-domain/src/main/generated/com/yellobook/domains/common/entity/QBaseEntity.java
  yellobook-domain/src/main/generated/com/yellobook/domains/inform/entity/QInform.java
  yellobook-domain/src/main/generated/com/yellobook/domains/inform/entity/QInformComment.java
  yellobook-domain/src/main/generated/com/yellobook/domains/inform/entity/QInformMention.java
  yellobook-domain/src/main/generated/com/yellobook/domains/inventory/entity/QInventory.java
  yellobook-domain/src/main/generated/com/yellobook/domains/inventory/entity/QProduct.java
  yellobook-domain/src/main/generated/com/yellobook/domains/member/entity/QMember.java
  yellobook-domain/src/main/generated/com/yellobook/domains/order/entity/QOrder.java
  yellobook-domain/src/main/generated/com/yellobook/domains/order/entity/QOrderComment.java
  yellobook-domain/src/main/generated/com/yellobook/domains/order/entity/QOrderMention.java
  yellobook-domain/src/main/generated/com/yellobook/domains/team/entity/QParticipant.java
  yellobook-domain/src/main/generated/com/yellobook/domains/team/entity/QTeam.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantRepository.java
  yellobook-domain/src/test/java/com/yellobook/config/ParticipantRepositoryTestConfig.java
  yellobook-domain/src/test/java/com/yellobook/config/TeamRepositoryTestConfig.java
  yellobook-domain/src/test/java/com/yellobook/domains/team/repository/ParticipantRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/team/repository/TeamRepositoryTest.java
Labels: ♻️refactor, ✅test, 🛠️bugfix

#50 [Feature/YB-337]: 주문시 재고 조회 API
  yellobook-api/src/main/java/com/yellobook/domains/inventory/controller/InventoryController.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/request/AddProductRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/request/ModifyProductAmountRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/response/GetProductsNameResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/response/GetSubProductNameResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/mapper/ProductMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/service/InventoryQueryService.java
  yellobook-api/src/main/java/com/yellobook/domains/order/controller/OrderController.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/request/AddOrderCommentRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/request/MakeOrderRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/response/AddOrderCommentResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/response/GetOrderCommentsResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/response/MakeOrderResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/order/service/OrderQueryService.java
  yellobook-api/src/test/java/com/yellobook/domains/inventory/controller/InventoryControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domains/inventory/service/InventoryQueryServiceTest.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/dto/query/QueryProductName.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/dto/query/QuerySubProduct.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/entity/Product.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/InventoryRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/ProductRepositoryCustom.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/repository/ProductRepositoryCustomImpl.java
  yellobook-domain/src/test/java/com/yellobook/domains/inventory/repository/InventoryRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/member/repository/MemberRepositoryTest.java
Labels: 📝docs, ✅test, ✨feature

#53 [Feature/YB-373] 팀내 모든 멤버 조회기능 추가
  yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/TeamMemberListResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/mapper/TeamMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamQueryService.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/dto/query/QueryOrder.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/dto/query/QueryTeamMember.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepositoryImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/TeamCustomRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/TeamCustomRepositoryImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/TeamRepository.java
Labels: ✨feature

#55 [Chore/YB-382] domain 모듈 테스트 설정 개선
  yellobook-api/src/main/java/com/yellobook/domains/inform/controller/InformController.java
  yellobook-api/src/main/java/com/yellobook/domains/inform/service/InformCommandService.java
  yellobook-api/src/main/java/com/yellobook/domains/member/controller/MemberController.java
  yellobook-api/src/main/java/com/yellobook/domains/member/service/MemberCommandService.java
  yellobook-api/src/main/java/com/yellobook/swagger/OpenAPiCustomConfig.java
  yellobook-api/src/test/java/com/yellobook/domains/member/controller/MemberControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domains/member/service/MemberCommandServiceTest.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/repository/OrderRepositoryCustomImpl.java
  yellobook-domain/src/test/java/com/yellobook/config/ParticipantRepositoryTestConfig.java
  yellobook-domain/src/test/java/com/yellobook/domains/inventory/repository/InventoryRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/member/repository/MemberRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/order/repository/OrderRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/schedule/repository/ScheduleRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/team/repository/ParticipantRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/team/repository/TeamRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/support/annotation/RepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/support/config/TestJpaConfig.java
  yellobook-domain/src/test/java/com/yellobook/support/config/TestQuerydslConfig.java
  yellobook-domain/src/test/java/com/yellobook/support/config/TestRepositoryConfig.java
  yellobook-domain/src/test/resources/cleanup.sql
  yellobook-domain/src/test/resources/cleanup_order.sql
Labels: ⚙️config

#57 [Feature/YB-376]: 재고, 주문 도메인에서 페이징, 조회 에러 등 수정
  .github/pull_request_template.md
  yellobook-api/src/main/java/com/yellobook/domains/inventory/controller/InventoryController.java
  yellobook-api/src/main/java/com/yellobook/domains/member/controller/MemberController.java
  yellobook-api/src/main/java/com/yellobook/domains/member/dto/response/ProfileResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/member/mapper/MemberMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/member/service/MemberQueryService.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/response/GetOrderCommentsResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/order/mapper/OrderMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/order/service/OrderQueryService.java
  yellobook-api/src/test/java/com/yellobook/domains/inventory/controller/InventoryControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domains/member/controller/MemberControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domains/member/service/MemberQueryServiceTest.java
  yellobook-api/src/test/java/com/yellobook/domains/order/service/OrderQueryServiceTest.java
  yellobook-domain/src/main/java/com/yellobook/domains/order/repository/OrderRepositoryCustomImpl.java
  yellobook-domain/src/test/resources/setup_order.sql
Labels: 🚑hotfix, 📝docs, ✅test

#59 [Chore/YB-412] CI/CD 파이프라인 추가설정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  build.gradle
Labels: ⚙️config, 🧤Infra

#62 [Chore/YB-427]: 통합테스트 환경 구성
  .github/workflows/cd.yml
  build.gradle
  yellobook-api/build.gradle
  yellobook-api/src/integration-test/java/.gitkeep
  yellobook-api/src/integration-test/resources/.gitkeep
  yellobook-api/src/main/java/com/yellobook/common/aop/TeamAdminOnlyAspect.java
  yellobook-api/src/main/java/com/yellobook/common/aop/TeamOrdererOnlyAspect.java
  yellobook-api/src/main/java/com/yellobook/common/aop/annotation/TeamAdminOnly.java
  yellobook-api/src/main/java/com/yellobook/common/aop/annotation/TeamOrdererOnly.java
  yellobook-api/src/main/java/com/yellobook/common/resolver/TeamMemberArgumentResolver.java
  yellobook-api/src/main/java/com/yellobook/common/resolver/annotation/TeamMember.java
  yellobook-api/src/main/java/com/yellobook/common/validation/annotation/ExistInform.java
  yellobook-api/src/main/java/com/yellobook/common/validation/annotation/ExistOrder.java
  yellobook-api/src/main/java/com/yellobook/common/validation/validator/ExistInformValidator.java
  yellobook-api/src/main/java/com/yellobook/common/validation/validator/ExistOrderValidator.java
  yellobook-api/src/main/java/com/yellobook/domains/auth/controller/AuthController.java
  yellobook-api/src/main/java/com/yellobook/domains/inform/controller/InformController.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/controller/InventoryController.java
  yellobook-api/src/main/java/com/yellobook/domains/member/controller/MemberController.java
  yellobook-api/src/main/java/com/yellobook/domains/order/controller/OrderController.java
  yellobook-api/src/main/java/com/yellobook/domains/schedule/controller/ScheduleController.java
  yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
  yellobook-api/src/test/java/com/yellobook/domains/member/controller/MemberControllerTest.java
Labels: ⚙️config

#60 [Test/YB-230] 팀 도메인 Service Unit Test 추가
  yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamQueryService.java
  yellobook-api/src/test/java/com/yellobook/domains/team/service/TeamCommandServiceTest.java
  yellobook-api/src/test/java/com/yellobook/domains/team/service/TeamQueryServiceTest.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepository.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/ParticipantCustomRepositoryImpl.java
  yellobook-domain/src/main/java/com/yellobook/domains/team/repository/TeamCustomRepositoryImpl.java
  yellobook-domain/src/test/java/com/yellobook/domains/team/repository/ParticipantRepositoryTest.java
  yellobook-domain/src/test/java/com/yellobook/domains/team/repository/TeamRepositoryTest.java
Labels: 🚑hotfix, ♻️refactor, ✅test

#63 [Chore/YB-432] testFixtures 도입
  yellobook-api/build.gradle
  yellobook-domain/build.gradle
  yellobook-domain/src/testFixtures/java/fixture/InformFixture.java
  yellobook-domain/src/testFixtures/java/fixture/InventoryFixture.java
  yellobook-domain/src/testFixtures/java/fixture/MemberFixture.java
  yellobook-domain/src/testFixtures/java/fixture/OrderFixture.java
  yellobook-domain/src/testFixtures/java/fixture/TeamFixture.java
  yellobook-domain/src/testFixtures/java/support/ReflectionUtils.java
Labels: ⚙️config

#61 [Feature/YB-350]: 엑셀 파일 변환 및 저장 구현
  yellobook-api/build.gradle
  yellobook-api/src/main/java/com/yellobook/domains/inventory/controller/InventoryController.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/cond/ExcelProductCond.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/request/AddProductRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/request/ModifyProductAmountRequest.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/dto/response/AddInventoryResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/mapper/InventoryMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/mapper/ProductMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/service/InventoryCommandService.java
  yellobook-api/src/main/java/com/yellobook/domains/inventory/utils/ExcelReadUtil.java
  yellobook-api/src/main/java/com/yellobook/domains/order/controller/OrderController.java
  yellobook-api/src/main/java/com/yellobook/domains/order/dto/request/MakeOrderRequest.java
  yellobook-api/src/test/java/com/yellobook/domains/inventory/controller/InventoryControllerTest.java
  yellobook-api/src/test/java/com/yellobook/domains/inventory/service/InventoryCommandServiceTest.java
  yellobook-api/src/test/java/com/yellobook/domains/order/controller/OrderControllerTest.java
  yellobook-common/src/main/java/com/yellobook/error/code/FileErrorCode.java
  yellobook-domain/src/main/java/com/yellobook/domains/inventory/entity/Product.java
Labels: ✨feature

#56 [Test/YB-229] 팀 도메인 Controller Unit Test 작성
  yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
  yellobook-api/src/main/java/com/yellobook/domains/team/dto/response/LeaveTeamResponse.java
  yellobook-api/src/main/java/com/yellobook/domains/team/mapper/TeamMapper.java
  yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamCommandService.java
  yellobook-api/src/test/java/com/yellobook/domains/team/controller/TeamControllerTest.java
Labels: ✅test
